#ifndef __EXCEPTIONS_H__
#define __EXCEPTIONS_H__

enum Exceptions {
	a_DONT_USE_THIS_EXCEPTION = 100,
	ALIGNMENT_LENGTH_MISMATCH_EXCEPTION,
	CBRUNS_DEBUGGING_EXCEPTION,
	CBRUNS_TODO_CODE_EXCEPTION,
	GAP_MODEL_PROBLEM_EXCEPTION,
	NO_SUCH_FILE_EXCEPTION
};

#endif
