#include <iostream>
#include <fstream>
#include "AlignmentMethod.h"
#include "BioSequence.h"

using namespace std;

int main (int argc, char * const argv[]) {

	BioSequence s2 = "WWWWWWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCCCCCCCCC";
	BioSequence s1 = "WWWWWWWWWWCCCCCCCCCC";
	
	SequenceAlignment a1 = s1;
	SequenceAlignment a2 = s2;
	
	cout << a1.align(a2);
	
    return 0;
}
